baseurl = "https://briandatablog.rbind.io/"
languageCode = "en-us"
title = "Brian's Data Blog"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name="Home"
    url = "/"
    weight=1

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Categories"
    url = "/categories/"
[[menu.main]]
    name = "Tags"
    url = "/tags/"

[social]
    github  = "https://github.com/BrianOB/briandatablog"
    twitter = "https://twitter.com/brianbupdate"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "college_lodge.png"
    width = 75
    height = 75
    alt = "Logo"
