---
title: Coronavirus test data
author: Brian Bowling
date: '2020-04-14'
slug: coronavirus-test-data
categories:
  - misc
tags:
  - stats
---

```{r libraries, include=F}

library(tidyverse)
library(DT)

# load data
load(file='D:/Documents/projects/data_workshop/data_processed/cdc_test_data.RData')

```


The Centers for Disease Control give a daily update on the number of Covid-19 tests reported to the agency. Here's the data as of April 14.

```{r table, echo=F}

cdc_test_data %>% 
  select(date, lab_type, tests) %>% 
  datatable()


```

The CDC notes that the data for last 7 days is incomplete due to reporting delays. Here's a graph of the days with full data.

```{r graph, echo=F}

full_data_date <- cdc_test_data %>% 
  filter(lab_type=='public_health_labs', nchar(note) == 0) %>% 
  summarise(max_date = max(date)) %>% 
  pull(max_date)

cdc_test_data %>% 
  filter(date <= full_data_date) %>% 
  group_by(date) %>% 
  summarise(tests=sum(tests)) %>% 
  ggplot(aes(x=date, y=tests, group=1)) +
  geom_line() +
  scale_x_date() +
  scale_y_continuous(labels=scales::comma) +
  labs(title='Covid-19 testing in the United States',
       x='',
       y='Number of tests reported',
       caption= 'Source:CDC\nNote: Data for last 7 days not shown because CDC says it\'s incomplete.\nThe periodic drops occur on weekends.')


```

